In [1]:
import pandas as pd

In [2]:
user = pd.read_csv("user_info(0801-1231).csv")

In [3]:
user.head()

id birthday  level     name sex                               sign
0  1000043185    03-04      4   骑在墙头找糖   女                        希望你磕的CP都是真的
1   100004596      NaN      4    无救小可爱  保密  积极者相信只有推动自己才能推动世界，只要推动自己就能推动世界。\n
2   100006120      NaN      4     花盛花葬  保密                                NaN
3   100006757    07-04      6  西花厅の海棠花  保密                                NaN
4  1000081881      NaN      2  说好话给我听过  保密                                NaN

In [4]:
user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 235156 entries, 0 to 235155
Data columns (total 6 columns):
 #   Column    Non-Null Count   Dtype 
---  ------    --------------   ----- 
 0   id        235156 non-null  int64 
 1   birthday  128971 non-null  object
 2   level     235156 non-null  int64 
 3   name      235156 non-null  object
 4   sex       235156 non-null  object
 5   sign      83081 non-null   object
dtypes: int64(2), object(4)
memory usage: 10.8+ MB


In [5]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

In [6]:
user_sex=user['sex']

In [7]:
user_sex_list=list(user_sex)

In [8]:
user_sex_list

['女',
 '保密',
 '保密',
 '保密',
 '保密',
 '男',
 '男',
 '保密',
 '男',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '男',
 '保密',
 '保密',
 '保密',
 '男',
 '保密',
 '保密',
 '女',
 '保密',
 '保密',
 '女',
 '保密',
 '保密',
 '保密',
 '保密',
 '女',
 '保密',
 '男',
 '保密',
 '女',
 '保密',
 '保密',
 '男',
 '男',
 '保密',
 '男',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '女',
 '保密',
 '保密',
 '保密',
 '保密',
 '女',
 '保密',
 '女',
 '保密',
 '男',
 '男',
 '保密',
 '保密',
 '保密',
 '保密',
 '男',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '男',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '男',
 '女',
 '保密',
 '女',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '女',
 '保密',
 '保密',
 '保密',
 '男',
 '女',
 '保密',
 '保密',
 '女',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '女',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '男',
 '女',
 '男',
 '男',
 '保密',
 '保密',
 '保密',
 '女',
 '男',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '保密',
 '男',
 '保密',
 '女',
 '保密',
 '女',
 '保密',
 '男',
 '保密',
 '保密',
 '男

In [9]:
le.fit(user_sex_list)

# >>> list(le.classes_)
# ['amsterdam', 'paris', 'tokyo']
# >>> le.transform(["tokyo", "tokyo", "paris"]) 
# array([2, 2, 1]...)
# >>> list(le.inverse_transform([2, 2, 1]))
# ['tokyo', 'tokyo', 'paris']

LabelEncoder()

In [10]:
list(le.classes_)

['保密', '女', '男']

In [18]:
le.transform(["保密"]) 

array([0])

In [19]:
le.transform(["男"]) 

array([2])

In [13]:
user['sex_em']=''

In [20]:
user.head()

id birthday  level     name sex                               sign  \
0  1000043185    03-04      4   骑在墙头找糖   女                        希望你磕的CP都是真的   
1   100004596      NaN      4    无救小可爱  保密  积极者相信只有推动自己才能推动世界，只要推动自己就能推动世界。\n   
2   100006120      NaN      4     花盛花葬  保密                                NaN   
3   100006757    07-04      6  西花厅の海棠花  保密                                NaN   
4  1000081881      NaN      2  说好话给我听过  保密                                NaN   

  sex_em  
0         
1         
2         
3         
4

In [16]:
from tqdm import tqdm

In [22]:
for i in tqdm(range(len(user))):
    if user['sex'][i]=='保密':
        user['sex_em'][i]=0 
    elif user['sex'][i]=='男':
        user['sex_em'][i]=2
    else:
        user['sex_em'][i]=1

  0%|                                                                                       | 0/235156 [00:00<?, ?it/s]C:\Users\11275\AppData\Local\Temp/ipykernel_58880/2591029991.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  user['sex_em'][i]=1
C:\Users\11275\AppData\Local\Temp/ipykernel_58880/2591029991.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  user['sex_em'][i]=0
C:\Users\11275\AppData\Local\Temp/ipykernel_58880/2591029991.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable

In [23]:
user.head()

id birthday  level     name sex                               sign  \
0  1000043185    03-04      4   骑在墙头找糖   女                        希望你磕的CP都是真的   
1   100004596      NaN      4    无救小可爱  保密  积极者相信只有推动自己才能推动世界，只要推动自己就能推动世界。\n   
2   100006120      NaN      4     花盛花葬  保密                                NaN   
3   100006757    07-04      6  西花厅の海棠花  保密                                NaN   
4  1000081881      NaN      2  说好话给我听过  保密                                NaN   

  sex_em  
0      1  
1      0  
2      0  
3      0  
4      0

In [24]:
user=user.drop(["name","sex","sign"],axis=1)

In [25]:
user.head()

id birthday  level sex_em
0  1000043185    03-04      4      1
1   100004596      NaN      4      0
2   100006120      NaN      4      0
3   100006757    07-04      6      0
4  1000081881      NaN      2      0

In [26]:
user.to_csv("user_em.csv",encoding="utf-8")

In [ ]:
import pandas as pd
import jieba
import re
import numpy as np
import gensim
from gensim.models import Word2Vec
import logging
logging.basicConfig(format='%(asctime)s : %(levelname)s : %(message)s', level=logging.INFO)

In [ ]:
def extract_word(wordlist):
    wlist=[]
    word=str(wordlist)
    r1 = "[a-zA-Z0-9\s+\.\!\/_,$%^*(+\"\']+|[+——！，。？、：；;《》“”~@#￥%……&*（）]+"
    #     word=re.sub(r1,'',word)
    word = re.sub(r1, '',word)
    wlist.append(word)
    return wlist

In [ ]:
list_num='积极者相信只有推动自己才能推动世界，只要推动自己就能推动世界。s+\.\!\/_,$%^*(+\"\']+|[+—'

In [ ]:
list_n=extract_word(list_num)
print(list_n)

In [ ]:
def cut_stop(s):
    stop_list =['「','」','‖','【','】','🎵','🤩','～','°͜ʖ͡°','✧',')',
                '-','|','♥',' ','｜','•','❀','☽','〕','〔','❤️','♪','♬',
                '˘','︶','♡',':','『','☞','✌️','🌿','😂','😎','』','］',
                '［',']','[','°','✾','✿','〖','〗','☺️','?','㊗️',"ʖ͡'",
                '❤️','✨','🦋','·','×','⑦','>',"｀･∧･´",'з','∠',
                '丨',"≧﹏≦",'×','▷','▶','◀','◁','❤','🌕','·','❤️','㊗️','✌️','☺️','💫']
    words =''
    for word in s:
        if word not in stop_list:
            words += word
        else:
            words += ""
    return words

In [ ]:
def cutword(word_list): 
    temp = jieba.lcut(word_list)  #结巴分词 精确模式
    words = []
    for i in temp:
        #过滤掉所有的标点符号
        i = re.sub("[\s+\.\!\/_,$%^*(+\"\'””《》]+|[+——！，。？、~@#￥%……&*（）：；‘]+「", "", i)
        if len(i) > 0:
            words.append(i)
#     if len(words) > 0:
#         lines.append(words)
#     print(lines[0:5])#预览前5行分词结果
    return words

In [ ]:
cutword(list_n)

In [ ]:
def finalcut(word_list):
    word=extract_word(word_list)
    wlist=cut_stop(word)
    wordlist=cutword(wlist)
    return wordlist

In [ ]:
from gensim.models import KeyedVectors
def load_word2vec_model(w2v_path):
    # load word2vec
    model =KeyedVectors.load_word2vec_format(w2v_path, binary=True)
    return model
model = load_word2vec_model('Word2Vec.bin')

In [ ]:
from gensim.models import Word2Vec
def getwordvec(word_list):
    word_vec=[]
    for w in finalcut(word_list):
        try:
            wordem=model.get_vector(w)
            word_vec.extend(wordem)
        except Exception as E:
#             print(E)
            continue
#         print(w)
    return word_vec

In [ ]:
user['name_em']=''
user['sign_em']=''

In [ ]:
for i in tqdmdmdmdm(range(len(user))):
    user['name_em'][i]=getwordvec(namer['name'])

In [ ]:
for i in tqdm(range(len(user))):
    user['sign_em'][i]=getwordvec(user['sign'])

In [ ]:
user.head()

In [ ]:
user.info()

In [ ]:
user.drop(["name","sex","sign"],axis=isinplace=ace=ace=ace=is=1,inplace=True)#就地更改

In [ ]:
user.to_csv("user_info_em.csv",encoding="utf-8")